# R Programming — NPTEL Week 4 Notes: All Commands

**Source:** *Foundations of R Software* (Shalabh, Dept. of Mathematics & Statistics, IIT Kanpur) — NPTEL
**Lectures covered:** 13 (Matrix Operations — Row, Column & Other Operations), 14 (Matrix Operations — Access and Mathematical Operations), 15 (Matrix Operations — Mathematical and Other Operations), 16 (Logical Operators), 17 (Relational and Logical Operators)

This notebook collects every R command shown in the notes, in the same order, organized under the same section headings, and executes each one so the output can be checked against the notes.

## Lecture 13 — Matrix Operations: Row, Column & Other Operations

### Renaming the Row and Column Names

In [1]:
x = matrix( nrow=4, ncol=3, data=c(1:12) )
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

`rownames(x)` renames the row names; `colnames(x)` renames the column names.

In [2]:
rownames(x) = c("r1", "r2", "r3", "r4")
x

   [,1] [,2] [,3]
r1 1    5     9
r2 2    6    10
r3 3    7    11
r4 4    8    12

In [3]:
colnames(x) = c("c1", "c2", "c3")
x

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

### Assigning a Specified Number to All Matrix Elements

In [4]:
x = matrix( nrow=4, ncol=2, data=2 )
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

### Diagonal Matrix

Construction of a diagonal matrix, here the identity matrix of dimension 3:

In [5]:
d = diag(1, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

Construction of a diagonal matrix with all numbers as 5, of dimension 3:

In [6]:
d = diag(5, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

### Transpose

Transpose of a matrix X: X'

In [7]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T )
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [8]:
xt = t(x)
xt

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

### Row and Column Sums

`rowSums(x)` finds the sum of numbers in rows; `colSums(x)` finds the sum of numbers in columns.

In [9]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [10]:
rowSums(x)

[1]  6  8 10 12

In [11]:
colSums(x)

[1] 10 26

### Row and Column Means

`rowMeans(x)` finds the means of rows; `colMeans(x)` finds the means of columns.

In [12]:
rowMeans(x)

[1] 3 4 5 6

In [13]:
colMeans(x)

[1] 2.5 6.5

## Lecture 14 — Matrix Operations: Access and Mathematical Operations

### Access to Rows, Columns or Submatrices

In [14]:
x = matrix( nrow=5, ncol=3, byrow=T, data=1:15)
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

In [15]:
x[3,]

[1] 7 8 9

In [16]:
x[,2]

[1]  2  5  8 11 14

In [17]:
x[4:5, 2:3]

     [,1] [,2]
[1,] 11   12
[2,] 14   15

In [18]:
x[c(1,4), c(1,3)]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

Looking at the outcome of `x[,2]` alone (`[1] 2 5 8 11 14`), it is not possible to know whether it is a row or a column — both return a plain vector.

### Addition of a Matrix with a Constant

Every element is added with the scalar.

In [19]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [20]:
x+5

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

### Subtraction of a Matrix with a Constant

Every element is subtracted by the scalar.

In [21]:
x - 5

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

## Lecture 15 — Matrix Operations: Mathematical and Other Operations

### Multiplication of a Matrix with a Constant

Every element is multiplied by the scalar.

In [22]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [23]:
5*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

### Division of a Matrix with a Constant

Every element is divided by the scalar.

In [24]:
x/2

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

### Addition and Subtraction of Matrices

Addition and subtraction of matrices (of the same dimensions) can be executed with the usual operators `+` and `-`.

In [25]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=4, ncol=2, data=11:18, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [26]:
y

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16
[4,] 17   18

In [27]:
x + y

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

In [28]:
x - y

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

**Example:**

In [29]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [30]:
4*x

     [,1] [,2]
[1,]  4    8
[2,] 12   16
[3,] 20   24
[4,] 28   32

In [31]:
x + 4*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

In [32]:
4*x - x

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

### Multiplication of Matrices

Multiplication of matrices can be executed with the operator `%*%`.

In [33]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=2, ncol=4, data=11:18, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [34]:
y

     [,1] [,2] [,3] [,4]
[1,] 11   12   13   14
[2,] 15   16   17   18

In [35]:
x%*%y

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

In [36]:
y%*%x

     [,1] [,2]
[1,] 210  260
[2,] 274  340

Another example: consider the multiplication of X' and X.

In [37]:
t(x)

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [38]:
t(x) %*% x

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [39]:
x %*% t(x)

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

Cross product of a matrix X, X'X, with `crossprod()`. `crossprod()` executes the multiplication faster than the conventional method with `t(x)%*%x`.

In [40]:
crossprod(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

### Concatenating Matrices

Concatenating matrices row-wise: `rbind(x, y)`. Concatenating matrices column-wise: `cbind(x, y)`.

In [41]:
x = matrix(nrow=3, ncol=2, data=1:6, byrow=T)
y = matrix(nrow=3, ncol=2, data=11:16, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

In [42]:
y

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16

In [43]:
rbind(x, y)

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

In [44]:
cbind(x, y)

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

### Inverse of Matrix

`solve()` finds the inverse of a positive definite matrix.

In [45]:
y = matrix( nrow = 2, ncol = 2, byrow = T, data = c(84,100,100,120))
y

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [46]:
solve(y)

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

### Eigen Values and Eigen Vectors of Matrix

`eigen()` finds the eigenvalues and eigenvectors of a positive definite matrix.

In [47]:
eigen(y)

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

## Lecture 16 — Logical Operators

### Logical Operators and Comparisons

| Operator | Executions |
|---|---|
| `>` | Greater than |
| `>=` | Greater than or equal |
| `<` | Less than |
| `<=` | Less than or equal |
| `==` | Exactly equal to |
| `!=` | Not equal to |
| `!` | Negation (not) |
| `&`, `&&` | and |
| `\|`, `\|\|` | or |
| `xor(x,y)` | either... or (exclusive) |
| `isTRUE(x)` | test if x is TRUE |
| `isFALSE(x)` | test if x is FALSE |
| `TRUE` / `FALSE` | true / false |

The **shorter form** (`&`, `|`) performs element-wise comparisons in almost the same way as arithmetic operators. The **longer form** (`&&`, `||`) evaluates left to right, examining only the first element of each vector — evaluation proceeds only until the result is determined.

### Examples: Use of `|` and `||`

In [48]:
x=8
(x < 10) || (x < 2)

[1] TRUE

In [49]:
x=18
(x < 10) || (x < 2)

[1] FALSE

`||` operates only on the first element and not on remaining elements; `|` operates on all the elements.

> **Note on R version:** the notes were recorded on an older R version, where `||`/`&&` on a length>1 vector silently used just the first element (with a warning). Since R 4.3.0, this is a hard **error** instead — `'length = 2' in coercion to 'logical(1)'`. The cell below is wrapped in `tryCatch()` so the real, current behavior is shown rather than hidden or faked.

In [50]:
x = c(8,18)
tryCatch(
  (x < 10) || (x < 2),
  error = function(e) e
)

In [51]:
(x < 10) | (x < 2)

[1]  TRUE FALSE

### Examples: Use of `&` and `&&`

In [52]:
x = 5
(x < 10) && (x > 2)

[1] TRUE

In [53]:
x = 15
(x < 10) && (x > 2)

[1] FALSE

`&&` operates only on the first element and not on remaining elements; `&` operates on all the elements.

> **Note on R version:** as above, `&&` on a length>1 vector is a hard error in this R version (4.3.3) rather than the old silent first-element behavior, so the cell below is wrapped in `tryCatch()` to show the real result.

In [54]:
x = c(8,18)
tryCatch(
  (x < 10) && (x > 2),
  error = function(e) e
)

In [55]:
(x < 10) & (x > 2)

[1]  TRUE FALSE

### Examples

In [56]:
x = 1:6        # Generates x=1,2,3,4,5,6
x

[1] 1 2 3 4 5 6

In [57]:
(x > 2) & (x < 5)  # Checks whether the values are greater than 2 and less than 5

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

In [58]:
x[(x > 2) & (x < 5)] # Finds which values are greater than 2 and smaller than 5

[1] 3 4

In [59]:
(x > 2) | (x < 5)  # Checks whether the values are greater than 2 or less than 5

[1] TRUE TRUE TRUE TRUE TRUE TRUE

In [60]:
x[(x > 2) | (x < 5)] # Finds which values are greater than 2 or smaller than 5

[1] 1 2 3 4 5 6

### Example of "The Longer Form Evaluates Left to Right Examining Only the First Element of Each Vector"

> **Note on R version:** the notes show `(x > 2) && (x < 5)` on a length-6 `x` silently evaluating as if only the first element were used, which was R's old behavior. In R 4.3.3 this is a hard error instead (`'length = 6' in coercion to 'logical(1)'`), so the cell below uses `tryCatch()` to show the real current result, immediately followed by the single-element version the notes say it is equivalent to.

In [61]:
x = 1:6        # Generates x = 1,2,3,4,5,6
tryCatch(
  (x > 2) && (x < 5),
  error = function(e) e
)

is equivalent to:

In [62]:
(x[1] > 2) & (x[1] < 5)   # Note that x[1] is only the first element in x

[1] FALSE

## Lecture 17 — Relational and Logical Operators

### Relational Operators and Comparisons

`TRUE` and `FALSE` are reserved words denoting logical constants. Zero is considered as `FALSE` and non-zero numbers are taken as `TRUE`.

| Operator | Executions |
|---|---|
| `>` | Greater than |
| `>=` | Greater than or equal |
| `<` | Less than |
| `<=` | Less than or equal |
| `==` | Exactly equal to |
| `!=` | Not equal to |
| `!` | Negation (not) |

### Logical Operators and Comparisons

| Operator | Executions | |
|---|---|---|
| `!` | Logical not | |
| `&` | Element-wise logical and | Performs operation element-wise |
| `&&` | Logical and | examines only the first element of the operands |
| `\|` | Element-wise logical or | Performs operation element-wise |
| `\|\|` | Logical or | examines only the first element of the operands |
| `xor(x,y)` | Either x or y (x or y but not x and y) | |
| `isTRUE(x)` | test if x is TRUE | |
| `isFALSE(x)` | test if x is FALSE | |
| `TRUE` / `FALSE` | true / false | |

### Example of Standard Logical Operations

Truth table — Statement 1 (x), Statement 2 (y), Outcome (x and y), Outcome (x or y):

| x | y | x and y | x or y |
|---|---|---|---|
| True | True | True | True |
| True | False | False | True |
| False | True | False | True |
| False | False | False | False |

In [63]:
x = TRUE
y = FALSE

In [64]:
x & y     # x AND y

[1] FALSE

In [65]:
x | y     # x OR y

[1] TRUE

In [66]:
!x         # negation of x

[1] FALSE

### Example

In [67]:
x = 5

In [68]:
Logical1 = (x > 2)
Logical1

[1] TRUE

In [69]:
is.logical(Logical1)

[1] TRUE

In [70]:
Logical2 = (x < 10)
Logical2

[1] TRUE

In [71]:
is.logical(Logical2)

[1] TRUE

In [72]:
Logical3 = (x != 5)
Logical3

[1] FALSE

In [73]:
is.logical(Logical3)

[1] TRUE

In [74]:
Logical4 = (2*x > 11)
Logical4

[1] FALSE

In [75]:
is.logical(Logical4)

[1] TRUE

In [76]:
Logical5 = (3*x <20)
Logical5

[1] TRUE

In [77]:
is.logical(Logical5)

[1] TRUE

### Examples

In [78]:
8 > 7

[1] TRUE

In [79]:
7 < 5

[1] FALSE

In [80]:
7 > 7

[1] FALSE

In [81]:
7 >= 7

[1] TRUE

In [82]:
8 < 8

[1] FALSE

In [83]:
8 <= 8

[1] TRUE

### Examples

In [84]:
8 != 9

[1] TRUE

In [85]:
9 != 9

[1] FALSE

In [86]:
7 == 7

[1] TRUE

In [87]:
7 == 8

[1] FALSE

In [88]:
x = TRUE
!x

[1] FALSE

### Examples

In [89]:
x = c(1, 2, 3)
y = c(4, 5, 6)

In [90]:
x > y        # Compares 1 > 4, 2 > 5, 3 > 6

[1] FALSE FALSE FALSE

In [91]:
x < y        # Compares 1 < 4, 2 < 5, 3 < 6

[1] TRUE TRUE TRUE

In [92]:
x != y       # Compares 1 != 4, 2 != 5, 3 != 6

[1] TRUE TRUE TRUE

In [93]:
x == y       # Compares 1 = 4, 2 = 5, 3 = 6

[1] FALSE FALSE FALSE

### Examples: `isTRUE()` and `isFALSE()`

In [94]:
isTRUE(8 < 6)   # Is 8 less than 6?

[1] FALSE

In [95]:
isTRUE(8 > 6)   # Is 8 greater than 6?

[1] TRUE

In [96]:
isFALSE(5 < 8)  # Is 5 less than 8?

[1] FALSE

In [97]:
isFALSE(5 > 8)  # Is 5 greater than 8?

[1] TRUE