In [1]:
%load_ext rpy2.ipython

# Formatting and Display of Strings

In [1]:
print("The zero occurs at", 2*pi, "radians.")

ERROR: Error in print.default("The zero occurs at", 2 * pi, "radians."): invalid 'quote' argument

In [2]:
print("The zero occurs at");
print(2*pi);
print("radians")

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"

#cat

In [3]:
print("The zero occurs at"); print(2*pi);
print("radians")

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"

In [4]:
cat("The zero occurs at", 2*pi, "radians.", "\n")

The zero occurs at 6.283185 radians.

In [5]:
d = date()
cat("Today’s date is:", d, "\n" )

Today’s date is: Mon Sep 21 08:47:45 2026

#Formatting and display of Strings

In [6]:
x = 1:10

In [7]:
cat(x, sep =" ++ ")

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10

In [8]:
 cat("\n")

In [9]:
cat(x, sep =" / ")

1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10

In [10]:
x = 7
cat("The square of", x, "is", x^2, "!\n")

The square of 7 is 49 !

In [11]:
cat("The square root of",x,"is approximately", format(sqrt(x),digits=3),"\n")

The square root of 7 is approximately 2.65

In [12]:
evenno = c(2,4,6,8,10)

In [13]:
cat("The first few even numbers are:", evenno, "...\n")

The first few even numbers are: 2 4 6 8 10 ...

In [14]:
cat(x, fill = 2, labels = paste("(", letters[1:10], "):"))

( a ): 7

# paste

In [15]:
paste(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [16]:
as.character(1:12)  #Alternative to paste

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [17]:
paste("Everybody", "loves", "R Programming.")

[1] "Everybody loves R Programming."

In [18]:
 paste("Everybody", "loves", "R Programming.",
sep="*")

[1] "Everybody*loves*R Programming."

In [19]:
paste("Everybody", "loves", "R Programming.",
sep="===")

[1] "Everybody===loves===R Programming."

In [20]:
names = c("Prof. Singh", "Mr.  Venkat", "Dr.
Jha")

In [21]:
 names

[1] "Prof. Singh" "Mr.  Venkat" "Dr. \nJha"

In [22]:
paste(names, "is", "a good", "person.")

[1] "Prof. Singh is a good person." "Mr.  Venkat is a good person."
[3] "Dr. \nJha is a good person."

In [23]:
names = c("Prof. Singh", "Mr.  Venkat", "Dr.
Jha")
 paste(names, "is", "a good", "person.",
collapse=", and ")

[1] "Prof. Singh is a good person., and Mr.  Venkat is a good person., and Dr. \nJha is a good person."

# Operations with Strings

In [24]:
paste(1, " is first", 2, " is second", 3, " is third",
sep = "#")

[1] "1# is first#2# is second#3# is third"

In [25]:
paste(1, " is first    ", 2, " is second     ", 3, " is
third    ", sep = "#")

[1] "1# is first    #2# is second     #3# is \nthird    "

In [26]:
x = paste("Ex", 1:5, sep="_")
x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

In [27]:
x = paste("Ex", 1:5, sep="_", collapse="")

In [28]:
paste0(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [29]:
paste0(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

# String Splitting

In [30]:
x = "The&!syntax&!of&!paste&!is!&available!
&inthe online-help"

In [31]:
x

[1] "The&!syntax&!of&!paste&!is!&available! \n&inthe online-help"

In [32]:
strsplit(x, split="!")

[[1]]
[1] "The&"                  "syntax&"               "of&"
[4] "paste&"                "is"                    "&available"
[7] " \n&inthe online-help"

In [33]:
strsplit(x, split = "&!")

[[1]]
[1] "The"                                 "syntax"
[3] "of"                                  "paste"
[5] "is!&available! \n&inthe online-help"

In [34]:
 y = strsplit(x, split = "!&")
 y

[[1]]
[1] "The&!syntax&!of&!paste&!is"      "available! \n&inthe online-help"

In [35]:
y[[1]][1]

[1] "The&!syntax&!of&!paste&!is"

In [36]:
y[[1]][2]

[1] "available! \n&inthe online-help"

In [37]:
y[[1]][3]

[1] NA

In [38]:
dates = c("2020-07-24", "2021-08-25", "2022
09-26", "2023-10-27")

In [39]:
datesplt = strsplit(dates, "-")

In [40]:
datesplt

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022\n09" "26"

[[4]]
[1] "2023" "10"   "27"

In [41]:
datemat = matrix(unlist(datesplt), nrow = 4,
ncol=3, byrow=TRUE)
datemat

Warning message in matrix(unlist(datesplt), nrow = 4, ncol = 3, byrow = TRUE):
“data length [11] is not a sub-multiple or multiple of the number of rows [4]”

     [,1]     [,2] [,3]
[1,] 2020     07   24
[2,] 2021     08   25
[3,] 2022\n09 26   2023
[4,] 10       27   2020

In [42]:
datematrix =
matrix(as.numeric(unlist(datesplt)), nrow = 4,
ncol=3, byrow=TRUE)

Warning message in matrix(as.numeric(unlist(datesplt)), nrow = 4, ncol = 3, byrow = TRUE):
“NAs introduced by coercion”
Warning message in matrix(as.numeric(unlist(datesplt)), nrow = 4, ncol = 3, byrow = TRUE):
“data length [11] is not a sub-multiple or multiple of the number of rows [4]”

In [43]:
datematrix

     [,1] [,2] [,3]
[1,] 2020  7     24
[2,] 2021  8     25
[3,]   NA 26   2023
[4,]   10 27   2020

In [44]:
 strsplit("Shalabh",split="")[[1]]

[1] "S" "h" "a" "l" "a" "b" "h"

# Manipulations with Strings and Alphabets

In [45]:
x = "R course 24.07.2022"
y = "Number of participants: 25"

In [46]:
nchar(x)

[1] 19

In [47]:
nchar(y)

[1] 26

In [48]:
nzchar(x)

[1] TRUE

In [49]:
nzchar(y)

[1] TRUE

In [50]:
x = c("Apple", "Banana", "Cake")
x

[1] "Apple"  "Banana" "Cake"

In [51]:
nzchar(x)

[1] TRUE TRUE TRUE

In [52]:
y = c("Apple", "", "Cake")
y

[1] "Apple" ""      "Cake"

In [53]:
nzchar(y)

[1]  TRUE FALSE  TRUE

In [57]:
x = c("Apple", "Banana", "Cake")

In [59]:
nchar(x)

[1] 5 6 4

In [60]:
y = c(2, 4, 6)

In [61]:
nchar(y)

[1] 1 1 1

In [62]:
z = c(11, 222, 3333)

In [63]:
nchar(z)

[1] 2 3 4

In [64]:
z1 = c(1.1, 2.22, 3.333)

In [65]:
nchar(z1)

[1] 3 4 5

# Lower and upper cases

In [66]:
x = "R course will start from 24.07.2022"

In [67]:
 toupper(x)

[1] "R COURSE WILL START FROM 24.07.2022"

In [68]:
z = "INDIAN INSTITUTE OF TECHNOLOGY"

In [69]:
tolower(z)

[1] "indian institute of technology"